"""empty message

Revision ID: 2a714c257a0f
Revises: 58c7a2f78b4f
Create Date: 2019-05-01 06:41:17.283769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a714c257a0f'
down_revision = '58c7a2f78b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_first_name', table_name='customers')
    op.drop_index('ix_customers_last_name', table_name='customers')
    op.drop_index('ix_products_payment_frequency', table_name='products')
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index('ix_transactions_type', table_name='transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_type', 'transactions', ['type'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('ix_products_payment_frequency', 'products', ['payment_frequency'], unique=False)
    op.create_index('ix_customers_last_name', 'customers', ['last_name'], unique=False)
    op.create_index('ix_customers_first_name', 'customers', ['first_name'], unique=False)
    # ### end Alembic commands ###
