"""empty message

Revision ID: 569069941f3c
Revises: 0085aacdfeac
Create Date: 2019-05-01 06:24:52.652879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '569069941f3c'
down_revision = '0085aacdfeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_ibfk_1', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'contracts', ['contract_id'], ['id'])
    op.drop_column('transactions', 'contract')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('contract', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_ibfk_1', 'transactions', 'contracts', ['contract'], ['id'])
    op.drop_column('transactions', 'contract_id')
    # ### end Alembic commands ###
