"""empty message

Revision ID: 655066f8da08
Revises: 2a714c257a0f
Create Date: 2019-05-01 18:32:41.923714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655066f8da08'
down_revision = '2a714c257a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_first_name'), 'customers', ['first_name'], unique=False)
    op.create_index(op.f('ix_customers_last_name'), 'customers', ['last_name'], unique=False)
    op.create_index(op.f('ix_products_payment_frequency'), 'products', ['payment_frequency'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_products_payment_frequency'), table_name='products')
    op.drop_index(op.f('ix_customers_last_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_first_name'), table_name='customers')
    # ### end Alembic commands ###
